version: '3.1'

services:

  site:
    container_name: 'site'
    image: medcmu/iteru-php-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./config/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - iteru-network

networks:
  iteru-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.124.1/24