version: '3.9'
services:
  web:
    container_name: 'web'
    image: medcmu/iteru-php-apache
    restart: always
    ports:
      - "8080:80"
    environment:
      WP_REDIS_HOST: "localhost.redis"
      WP_REDIS_PORT: "6379"
      WP_REDIS_PASSWORD: "password"
    deploy:
      resources:
        limits:
          memory: 768M
    memswap_limit: 768M
    ulimits:
      nofile: {
        soft: 65536,
        hard: 65536
      }
    volumes:
      - /path/to/web:/var/www/html
      - /path/to/config/cache-headers.conf:/etc/apache2/conf-enabled/10-cache-headers.conf:ro
      - /path/to/config/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf:ro
      - /path/to/config/base.ini:/usr/local/etc/php/conf.d/00-base.ini:ro
      - /path/to/config/opcache.ini:/usr/local/etc/php/conf.d/10-opcache.ini:ro
      - /path/to/config/redis.ini:/usr/local/etc/php/conf.d/20-redis.ini
    network-mode: bridge
